# Generated by Django 4.2.3 on 2023-08-06 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_delivery', models.CharField(max_length=50, verbose_name='Телефон доставки')),
                ('phone_seo', models.CharField(max_length=50, verbose_name='Телефон руководства')),
                ('email', models.CharField(max_length=50, verbose_name='E-mail')),
            ],
            options={
                'verbose_name': 'контакт',
                'verbose_name_plural': 'контакты',
            },
        ),
    ]